pip3 install scikit-learn 
pip3 install scipy
pip3 install numpy
pip3 install matplotlib
pip3 install pandas
pip3 install statsmodels  
pip3 install sklearn 
pip3 install tensorflow 
pip3 install keras